version: "3"
services:
  main_service:
    container_name: main_service
    build: .
    image: main_service
    restart: always
    depends_on:
      - minio
    env_file:
      - .env
    volumes:
      - ./pyproject.toml:/pyproject.toml
      - ./mlops_dz:/mlops_dz/
      - ./tests:/tests/
      - ./dashboard:/dashboard/
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8501:8501"

  minio:
    image: minio/minio
    container_name: minio_s3
    command: server /data --console-address :9001
    env_file:
      - .env
    volumes:
      - minio_data:/data

volumes:
  minio_data: